-- FounderHub NL — Supabase schema
-- Run this in your Supabase SQL editor

-- 1. Initiatives
create table if not exists initiatives (
  id integer primary key,
  name text not null,
  type text not null,
  secondary_type text default '',
  url text default '',
  organization text default '',
  access text default 'Application required',
  cost text default 'Free',
  notes text default '',
  province text default '',
  city text default '',
  industries jsonb default '[]',
  format text default '',
  updated_at timestamptz default now()
);

-- 2. Admin sessions
create table if not exists admin_sessions (
  token text primary key,
  expires_at timestamptz not null,
  created_at timestamptz default now()
);

-- 3. Claim requests
create table if not exists claims (
  id uuid primary key default gen_random_uuid(),
  initiative_id integer not null references initiatives(id),
  initiative_name text not null,
  claimant_name text not null,
  claimant_email text not null,
  claimant_org text default '',
  reason text default '',
  status text default 'pending',
  created_at timestamptz default now()
);

-- 4. Approved claimants
create table if not exists claimants (
  id uuid primary key default gen_random_uuid(),
  email text unique not null,
  password_hash text not null,
  initiative_ids integer[] default '{}',
  created_at timestamptz default now()
);

-- 5. Claimant sessions
create table if not exists claimant_sessions (
  token text primary key,
  claimant_id uuid not null references claimants(id),
  expires_at timestamptz not null
);

-- Disable RLS on all tables (these are accessed via service role key only)
alter table initiatives disable row level security;
alter table admin_sessions disable row level security;
alter table claims disable row level security;
alter table claimants disable row level security;
alter table claimant_sessions disable row level security;

-- Allow public read on initiatives only
alter table initiatives enable row level security;
create policy "Public read initiatives" on initiatives for select using (true);

-- ─── SEED DATA ───────────────────────────────────────────────────────────────
insert into initiatives (id, name, type, secondary_type, url, organization, access, cost, notes) values
(1, 'Circular Factory', 'Accelerator', '', 'https://www.circular-factory.com', 'Circular Factory', 'Application required', 'Free', ''),
(2, 'EIT Health', 'Accelerator', '', 'https://eithealth.eu', 'EIT Health', 'Application required', 'Free', ''),
(3, 'PortXL', 'Accelerator', '', 'https://www.portxl.org', 'PortXL', 'Application required', 'Free', ''),
(4, 'Mobility Lab', 'Accelerator', '', 'https://mobilitylab.nl/', 'Mobility Lab', 'Application required', 'Free', ''),
(5, 'ScaleNL', 'Accelerator', '', 'https://scalenl.com/', 'ScaleNL', 'Application required', 'Paid', ''),
(6, 'Yes!Delft', 'Accelerator', 'Incubator', 'https://www.yesdelft.com', 'Yes!Delft', 'Application required', 'Paid', 'Offers both incubation and acceleration programs'),
(7, 'BlueCity', 'Incubator', 'Campus / Coworking', 'https://www.bluecity.nl', 'BlueCity', 'Application required', 'Paid', 'Physical workspace in former Tropicana swimming pool; also open as event/meeting venue'),
(8, 'Forward Incubator', 'Incubator', '', 'https://www.newcomersforward.com/', 'Forward·Inc', 'Application required', 'Free', 'Focused on entrepreneurs with newcomer/refugee background; based at CIC Rotterdam'),
(9, 'Hortiheroes', 'Incubator', '', 'https://hortiheroes.com/', 'Hortiheroes', 'Application required', 'Free', 'Based at World Horti Center, Naaldwijk'),
(10, 'PLNT', 'Incubator', 'Campus / Coworking', 'https://www.plnt.nl', 'PLNT', 'Application required', 'Paid', 'Also a campus with open coworking memberships'),
(11, 'Biotech Campus Delft', 'Campus / Coworking', '', 'https://www.biotechcampusdelft.com', 'Biotech Campus Delft', 'Application required', 'Paid', ''),
(12, 'Leiden Bio Science Park', 'Campus / Coworking', '', 'https://leidenbiosciencepark.nl/', 'Leiden Bio Science Park', 'Application required', 'Paid', ''),
(13, 'Rotterdam Square', 'Campus / Coworking', '', 'https://www.rotterdamsquare.nl', 'Rotterdam Square', 'Open to all', 'Paid', ''),
(14, 'Space Campus', 'Campus / Coworking', '', 'https://www.nlspacecampus.eu/', 'Space Campus', 'Application required', 'Paid', ''),
(15, 'TU Delft Campus', 'Campus / Coworking', '', 'https://www.tudelftcampus.nl', 'TU Delft Campus', 'Application required', 'Paid', ''),
(16, 'Unmanned Valley', 'Campus / Coworking', '', 'https://unmannedvalley.nl/home/', 'Unmanned Valley', 'Application required', 'Paid', ''),
(17, 'The Green Village', 'Campus / Coworking', 'Support Program', 'https://www.thegreenvillage.org', 'The Green Village', 'Application required', 'Free', 'Innovation fieldlab at TU Delft for testing sustainable solutions'),
(18, '42Workspace', 'Campus / Coworking', '', 'https://42workspace.com', '42Workspace', 'Open to all', 'Paid', ''),
(19, 'Aerospace Innovation Hub', 'Campus / Coworking', '', 'https://aerospaceinnovationhub.nl/', 'Aerospace Innovation Hub', 'Application required', 'Paid', ''),
(20, 'Apollo14', 'Campus / Coworking', '', 'https://www.apollo14.nl', 'Apollo14', 'Open to all', 'Paid', ''),
(21, 'Biopartner', 'Campus / Coworking', '', 'https://www.biopartnerleiden.nl/', 'Biopartner', 'Application required', 'Paid', ''),
(22, 'Buccaneer Delft', 'Campus / Coworking', '', 'https://www.buccaneerdelft.com', 'Buccaneer Delft', 'Open to all', 'Paid', ''),
(23, 'Caballerofabriek', 'Campus / Coworking', '', 'https://www.caballerofabriek.nl', 'Caballerofabriek', 'Open to all', 'Paid', ''),
(24, 'Campus@Sea', 'Campus / Coworking', '', 'https://www.campusatsea.nl', 'Campus@Sea', 'Application required', 'Paid', ''),
(25, 'CIC Rotterdam', 'Campus / Coworking', '', 'https://cic.com/rotterdam', 'CIC Rotterdam', 'Open to all', 'Paid', ''),
(26, 'Dutch Innovation Factory', 'Campus / Coworking', '', 'https://community.dutchinnovationpark.nl/nl/', 'Dutch Innovation Factory', 'Open to all', 'Paid', ''),
(27, 'Duurzaamheidsfabriek', 'Campus / Coworking', '', 'https://www.duurzaamheidsfabriek.nl', 'Duurzaamheidsfabriek', 'Open to all', 'Paid', ''),
(28, 'Groothandelsgebouw', 'Campus / Coworking', '', 'https://www.groothandelsgebouw.nl', 'Groothandelsgebouw', 'Open to all', 'Paid', ''),
(29, 'House of Quantum', 'Campus / Coworking', '', 'https://www.houseofquantum.com/', 'House of Quantum', 'Application required', 'Paid', ''),
(30, 'Katoenhuis', 'Campus / Coworking', 'Community / Network', 'https://www.katoenhuis.nl/', 'Katoenhuis', 'Open to all', 'Paid', 'Also serves as physical hub for SHINE immersive tech network'),
(31, 'Keilewerf', 'Campus / Coworking', '', 'https://www.keilewerf.nl', 'Keilewerf', 'Open to all', 'Paid', ''),
(32, 'LaatBloeien', 'Campus / Coworking', '', 'https://www.laatbloeien.nl', 'LaatBloeien', 'Open to all', 'Paid', 'Impact-focused coworking at Hofplein Rotterdam'),
(33, 'Microlab', 'Campus / Coworking', '', 'https://www.microlab.nl', 'Microlab', 'Open to all', 'Paid', ''),
(34, 'NEXT Delft', 'Campus / Coworking', '', 'https://www.nextdelft.nl', 'NEXT Delft', 'Open to all', 'Paid', ''),
(35, 'ONS Schiedam', 'Campus / Coworking', '', 'https://www.onsschiedam.nl', 'ONS Schiedam', 'Open to all', 'Paid', ''),
(36, 'Planet b.io', 'Campus / Coworking', '', 'https://www.planet-b.io', 'Planet b.io', 'Application required', 'Paid', ''),
(37, 'Plant One', 'Campus / Coworking', '', 'https://www.plantone.nl', 'Plant One', 'Application required', 'Paid', ''),
(38, 'Platform Zero', 'Campus / Coworking', '', 'https://www.platformzero.co', 'Platform Zero', 'Application required', 'Paid', ''),
(39, 'Progress Bar', 'Campus / Coworking', '', 'https://www.progressbar.nl', 'Progress Bar', 'Open to all', 'Paid', ''),
(40, 'RDM Campus', 'Campus / Coworking', '', 'https://www.rdmrotterdam.nl', 'RDM Campus', 'Open to all', 'Paid', ''),
(41, 'Robohouse (TU Delft)', 'Campus / Coworking', '', 'https://www.robohouse.nl', 'Robohouse', 'Application required', 'Paid', ''),
(42, 'Rotterdam Science Tower', 'Campus / Coworking', '', 'https://www.rotterdamsciencetower.nl', 'Rotterdam Science Tower', 'Open to all', 'Paid', ''),
(43, 'Space Business Innovation Centre Noordwijk', 'Campus / Coworking', '', 'https://www.sbicnoordwijk.nl/startup-hub/', 'SBIC Noordwijk', 'Application required', 'Free', ''),
(44, 'The Hague Tech', 'Campus / Coworking', '', 'https://www.thehaguetech.com/', 'The Hague Tech', 'Open to all', 'Paid', ''),
(45, 'The Social Hub', 'Campus / Coworking', '', 'https://www.thesocialhub.co', 'The Social Hub', 'Open to all', 'Paid', ''),
(46, 'Titaan / Unknown Spaces', 'Campus / Coworking', '', 'https://titaan.unknown-spaces.com/', 'Titaan', 'Open to all', 'Paid', ''),
(47, 'Workspot', 'Campus / Coworking', '', 'https://workspot.nu/', 'Workspot', 'Open to all', 'Paid', ''),
(48, 'Up!Rotterdam', 'Community / Network', '', 'http://www.uprotterdam.com/', 'Up!Rotterdam', 'Open to all', 'Free', ''),
(49, 'Greenport West Holland', 'Community / Network', '', 'https://greenportwestholland.nl/', 'Greenport West Holland', 'Open to all', 'Free', ''),
(50, 'Hague Security Delta', 'Community / Network', '', 'https://www.securitydelta.nl', 'Hague Security Delta', 'Application required', 'Paid', ''),
(51, 'Incubators United', 'Community / Network', '', 'https://www.incubatorsunited.com/', 'Incubators United', 'Open to all', 'Free', ''),
(52, 'iTanks', 'Community / Network', '', 'https://www.itanks.eu', 'iTanks', 'Application required', 'Paid', ''),
(53, 'Medical Delta', 'Community / Network', '', 'https://www.medicaldelta.nl/', 'Medical Delta', 'Application required', 'Free', ''),
(54, 'North Sea Farmers', 'Community / Network', '', 'https://www.northseafarmers.org/', 'North Sea Farmers', 'Application required', 'Free', ''),
(55, 'Noorderwind', 'Community / Network', '', 'https://www.noorderwind.co/', 'Noorderwind', 'Application required', 'Free', 'Sustainable startup support collective'),
(56, 'Protein Port', 'Community / Network', '', 'https://www.proteinport.com/', 'Protein Port', 'Application required', 'Free', ''),
(57, 'Quantum Delta', 'Community / Network', '', 'https://www.quantumdelta.nl', 'Quantum Delta', 'Application required', 'Free', ''),
(58, 'Rotterdam Partners', 'Community / Network', '', 'https://www.rotterdampartners.nl', 'Rotterdam Partners', 'Open to all', 'Free', ''),
(59, 'SHINE', 'Community / Network', '', 'https://www.katoenhuis.nl/', 'SHINE / Katoenhuis', 'Application required', 'Free', 'Network for immersive tech (VR/AR/MR); physical hub at Katoenhuis Rotterdam'),
(60, 'Startup Grind Rotterdam', 'Community / Network', 'Event', 'https://www.startupgrind.com/rotterdam/', 'Startup Grind', 'Open to all', 'Free', 'Also organises regular events and meetups'),
(61, 'Techleap', 'Community / Network', '', 'https://techleap.nl', 'Techleap', 'Application required', 'Free', ''),
(62, 'Unify Energy', 'Community / Network', '', 'https://www.unify.energy/community-1', 'Unify Energy', 'Application required', 'Free', ''),
(63, 'Voorgoed Agency', 'Community / Network', '', 'https://www.voorgoedagency.nl/', 'Voorgoed Agency', 'Open to all', 'Free', 'Focus on social entrepreneurship in Rotterdam'),
(64, 'ImpactCity the Hague', 'Community / Network', '', 'https://www.impactcity.nl', 'ImpactCity', 'Open to all', 'Free', ''),
(65, 'ScaleBooster', 'Support Program', '', 'https://www.scalebooster.nl', 'ScaleBooster', 'Application required', 'Free', 'Zoetermeer-based growth program; runs ELITE accelerator track from March 2025'),
(66, 'The Hague & Partners', 'Support Program', '', 'https://thehague.com/partners/nl', 'The Hague & Partners', 'Open to all', 'Free', ''),
(67, 'HortiTech', 'Support Program', '', 'https://horti-tech.com/', 'HortiTech', 'Application required', 'Paid', 'R&D and education consultancy for greenhouse horticulture'),
(68, 'Accelerator Program', 'Accelerator', '', 'https://yesdelft.com/services/accelerator-program/', 'Yes!Delft', 'Application required', 'Paid', ''),
(69, 'AI Validation & Acceleration', 'Accelerator', '', 'https://mondai.tudelftcampus.nl/en/', 'Yes!Delft', 'Application required', 'Free', ''),
(70, 'Cyber Security Validation & Acceleration', 'Accelerator', '', 'https://yesdelft.com/events/cybersecurity/', 'Yes!Delft', 'Application required', 'Free', ''),
(71, 'ELITTE', 'Accelerator', '', 'https://www.ece.nl/scaleup-programmas/', 'ECE', 'Application required', 'Free', ''),
(72, 'Globaliser Program', 'Accelerator', '', 'https://dutchbasecamp.org/', 'DutchBasecamp', 'Application required', 'Free', ''),
(73, 'Green Chemistry Accelerator', 'Accelerator', '', 'https://groenechemie.nl/nl/green-chemistry-accelerator', 'Innovation Quarter', 'Application required', 'Free', ''),
(74, 'Health Tech Accelerator', 'Accelerator', '', 'https://www.innovationquarter.nl/health-tech-accelerator-2024-afgetrapt/', 'Innovation Quarter', 'Application required', 'Free', ''),
(75, 'Hortiscience Validation & Acceleration', 'Accelerator', '', 'https://hiceu.com/en/', 'Yes!Delft', 'Application required', 'Free', ''),
(76, 'Ignition Programme', 'Accelerator', '', 'https://www.sbicnoordwijk.nl/ignition-programme/', 'SBIC Noordwijk', 'Application required', 'Free', ''),
(77, 'Maritime Accelerator', 'Accelerator', '', 'https://portxl.org/about-us/why-join-portxl/', 'PortXL', 'Application required', 'Free', ''),
(78, 'Maritime Validation & Acceleration', 'Accelerator', '', 'https://yesdelft.com/events/maritime-industry-innovation-challenge/', 'Yes!Delft', 'Application required', 'Free', ''),
(79, 'MedTech Validation & Acceleration', 'Accelerator', '', 'https://yesdelft.com/events/validation-program-for-med-tech-startups/', 'Yes!Delft', 'Application required', 'Free', ''),
(80, 'New Energy Validation & Acceleration', 'Accelerator', '', 'https://newenergychallenge.com/', 'Yes!Delft', 'Application required', 'Free', ''),
(81, 'Pole Position Program', 'Accelerator', '', 'https://techleap.nl/programmes/pole-position/', 'Techleap', 'Application required', 'Free', ''),
(82, 'Rise Program', 'Accelerator', '', 'https://scaleups.techleap.nl/offer/rise', 'Techleap', 'Application required', 'Free', ''),
(83, 'Shine Program', 'Accelerator', '', 'https://scaleups.techleap.nl/offer/shine', 'Techleap', 'Application required', 'Free', ''),
(84, 'Soft Landing', 'Accelerator', '', 'https://www.sbicnoordwijk.nl/soft-landing-programme/', 'SBIC Noordwijk', 'Application required', 'Free', ''),
(85, 'Start Up & Lift Off', 'Accelerator', '', 'https://unmannedvalley.nl/su-lo/', 'Unmanned Valley', 'Application required', 'Free', ''),
(86, 'Startup in Residence', 'Accelerator', '', 'https://intergov.startupinresidence.com/', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(87, 'US Fasttrack', 'Accelerator', '', 'https://scalenl.com/programs/', 'ScaleNL', 'Application required', 'Paid', ''),
(88, 'Validation Program', 'Accelerator', '', 'https://yesdelft.com/services/validation-lab/', 'Yes!Delft', 'Application required', 'Paid', ''),
(89, 'Cyber Security Incubatieprogramma', 'Incubator', '', 'https://yesdelft.com/', 'Yes!Delft', 'Application required', 'Free', ''),
(90, 'ESA BIC Noordwijk', 'Incubator', '', 'https://www.sbicnoordwijk.nl/esa-bic/', 'SBIC Noordwijk', 'Application required', 'Free', ''),
(91, 'unlock_incubation', 'Incubator', '', 'https://plnt.nl/en/programs/unlock-incubation/', 'PLNT', 'Application required', 'Free', ''),
(92, 'Infinity', 'Community / Network', '', 'https://www.infinityqd.nl/', 'Quantum Delta', 'Application required', 'Free', ''),
(93, 'Planet B.io Community Program', 'Community / Network', '', 'https://www.planet-b.io/community/', 'Planet b.io', 'Application required', 'Free', ''),
(94, 'Smart Hydrogen Hub', 'Community / Network', '', 'https://www.rotterdammaritimecapital.com/news/we-are-building-the-smart-hydrogen-hub-for-and-with-m4h', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(95, 'WEC 500 Startup Community', 'Community / Network', '', 'https://platformzero.co/pz-events/', 'Platform Zero', 'Application required', 'Free', ''),
(96, 'ACCEZ voor innovators en leiders in (glas)tuinbouw', 'Support Program', '', 'https://accez.nl', 'ECE / Provincie Zuid Holland', 'Application required', 'Free', ''),
(97, 'Biotech Training Facility', 'Support Program', '', 'https://biotechtrainingfacility.com/en', 'Leiden Bio Science Park', 'Application required', 'Paid', ''),
(98, 'Business Innovation Program Food', 'Support Program', '', 'https://www.businessinnovationprogramfood.nl/151211', 'Innovation Quarter', 'Application required', 'Free', ''),
(99, 'CIRCO - Circular Design Tracks', 'Support Program', '', 'https://www.bluecity.nl/zakelijke-programma-s/circo-tracks', 'BlueCity', 'Application required', 'Paid', ''),
(100, 'Circulair Loket', 'Support Program', '', 'https://www.bluecity.nl/zakelijke-programma-s/circulair-loket', 'BlueCity', 'Open to all', 'Free', ''),
(101, 'Circulaire Ketenprojecten', 'Support Program', '', 'https://www.bluecity.nl/zakelijke-programma-s/circulaire-ketenprojecten', 'BlueCity', 'Application required', 'Free', ''),
(102, 'Circular Ideation Lab', 'Support Program', '', 'https://www.bluecity.nl/zakelijke-programma-s/circular-ideation-lab', 'BlueCity', 'Application required', 'Free', ''),
(103, 'Climate Tech Scale-up Support', 'Support Program', '', '', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(104, 'Dutch New Narrative Lab', 'Support Program', '', 'https://www.dnnl.org', 'ECE', 'Application required', 'Free', ''),
(105, 'Energie Financieringsdesk TKI', 'Support Program', '', 'https://topsectorenergie.nl/nl/subsidiemogelijkheden/financieringsloket/', 'Provincie Zuid Holland', 'Open to all', 'Free', ''),
(106, 'ESA Technology Broker NL', 'Support Program', '', 'https://www.esa-technology-broker.nl/', 'SBIC / Space Campus', 'Open to all', 'Free', ''),
(107, 'European Scaleup Institute', 'Support Program', '', 'https://scaleupinstitute.eu/', 'ECE', 'Application required', 'Free', ''),
(108, 'Het Groeicollege', 'Support Program', '', 'https://www.ece.nl/scaleup-programmas/', 'ECE', 'Application required', 'Free', ''),
(109, 'Impact Studio', 'Support Program', '', 'https://www.tudelft.nl/innovatie-impact/ondernemerschap/impact-studio', 'TU Delft', 'Application required', 'Free', ''),
(110, 'Investor Matching', 'Support Program', '', 'https://www.rotterdaminnovationcity.com/get-access-to/capital/phx/', 'Up!Rotterdam', 'Open to all', 'Free', ''),
(111, 'Market Readiness Program', 'Support Program', '', 'https://www.innovationquarter.nl/item/market-readiness-program/', 'Innovation Quarter', 'Application required', 'Free', ''),
(112, 'Nieuwe Nassen', 'Support Program', '', 'https://www.bluecity.nl/zakelijke-programma-s/het-nieuwe-nassen', 'BlueCity', 'Application required', 'Free', ''),
(113, 'Orchestrating Innovation in Public & Private Ecosystems', 'Support Program', '', 'https://uploads.ece.nl/pdf/ECE_Brochure_OI_2024_ENG.pdf', 'ECE / TNO', 'Application required', 'Paid', ''),
(114, 'Programma Energie & Klimaat', 'Support Program', '', 'https://www.innovationquarter.nl/item/energie-en-klimaat/', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(115, 'Programma Zorgtech', 'Support Program', '', 'https://www.innovationquarter.nl/item/zorgtech/', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(116, 'Ready to Start', 'Support Program', '', 'https://plnt.nl/en/programs/ready-to-start/', 'PLNT', 'Open to all', 'Free', ''),
(117, 'Smart Energy Systems', 'Support Program', '', 'https://www.ondernemen010.nl/smart-energy-systems/', 'Gemeente Rotterdam', 'Application required', 'Free', ''),
(118, 'Startup Missies', 'Support Program', '', 'https://english.rvo.nl/topics/starten-op-buitenlandse-markten/start-ups', 'RVO / Up!Rotterdam', 'Application required', 'Free', ''),
(119, 'Startup Visa Softlanding', 'Support Program', '', 'https://www.startupvisa.nl/', 'CIC Rotterdam / 42Workspace / ECE', 'Application required', 'Free', ''),
(120, 'Student Founder Programme', 'Support Program', '', 'https://ecestudents.nl/student-founders-programme/', 'ECE', 'Application required', 'Free', ''),
(121, 'TNO Fasttrack', 'Support Program', '', 'https://fasttrack.tno.nl/', 'TNO', 'Application required', 'Free', ''),
(122, 'TNO Tech Transfer', 'Support Program', '', 'https://www.tno.nl/en/collaboration/tech-transfer/', 'TNO', 'Open to all', 'Free', ''),
(123, 'TU Delft Startup Voucher Programme', 'Support Program', '', 'https://www.tudelftcampus.nl/entrepreneurship/tu-delft-startup-voucher-programme/', 'TU Delft', 'Application required', 'Free', ''),
(124, 'Innovatieprogramma Zorgtech', 'Support Program', '', 'https://www.medicaldelta.nl/samenwerkingen/innovatieprogramma-zorgtech', 'Medical Delta', 'Application required', 'Free', ''),
(125, 'Meet your Co-founder', 'Support Program', '', 'https://yesdelft.com/services/meet-your-co-founder/', 'Yes!Delft', 'Application required', 'Free', ''),
(126, 'Meet your Co-founder XL', 'Support Program', '', 'https://www.incubatorsunited.com/', 'Incubators United', 'Open to all', 'Free', ''),
(127, 'Maritime Investment Program', 'Support Program', '', '', 'Platform Zero', 'Application required', 'Free', ''),
(128, 'Campus Regeling Zuid Holland', 'Support Program', '', 'https://www.zuid-holland.nl/online-regelen/subsidies/subsidies/campussen-subsidie/', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(129, 'Bakkie Impact', 'Event', '', 'https://www.voorgoedagency.nl/bakkie-impact-opstroopsessie/', 'Voorgoed Agency', 'Open to all', 'Free', ''),
(130, 'CEO Dinners', 'Event', '', 'https://founderskeepers.io/', 'Up!Rotterdam', 'Application required', 'Free', ''),
(131, 'Championing Innovation in Turbulent Times', 'Event', '', 'https://form.typeform.com/to/Yl59WbfA', 'ECE', 'Open to all', 'Free', ''),
(132, 'Circular Challenge', 'Event', '', 'https://www.bluecity.nl/zakelijke-programma-s/circular-challenge', 'BlueCity', 'Application required', 'Free', ''),
(133, 'CXO Deepdives', 'Event', '', 'https://founderskeepers.io/', 'Up!Rotterdam', 'Application required', 'Free', ''),
(134, 'Erasmus University Challenge', 'Event', '', 'https://erasmusuniversitychallenge.nl/', 'Erasmus Enterprise', 'Application required', 'Free', ''),
(135, 'Expert Sessies', 'Event', '', 'https://buccaneerdelft.com/events/', 'Buccaneer Delft', 'Open to all', 'Free', ''),
(136, 'Festival van de Toekomst', 'Event', '', 'https://www.festivalvandetoekomst.nl/', 'Provincie Zuid Holland', 'Open to all', 'Free', ''),
(137, 'Founders Diner (BlueCity)', 'Event', '', '', 'BlueCity', 'Application required', 'Free', ''),
(138, 'Founders Dinners', 'Event', '', 'https://titaan.unknown-spaces.com/events/', 'Titaan / Unknown Campus', 'Open to all', 'Free', ''),
(139, 'Fuckup Nights', 'Event', '', 'https://www.bluecity.nl/fuckup-nights-rotterdam', 'BlueCity', 'Open to all', 'Free', ''),
(140, 'Hackathons', 'Event', '', 'https://www.bluecity.nl/zakelijke-programma-s/hackathons', 'BlueCity', 'Open to all', 'Free', ''),
(141, 'Hortiheroes Hackathon', 'Event', '', 'https://hortiheroes.com/career/hortiheroes-hackathon/', 'Hortiheroes', 'Open to all', 'Free', ''),
(142, 'Hydrogen Innovation Community Events', 'Event', '', '', 'Provincie Zuid Holland', 'Application required', 'Free', ''),
(143, 'Impact Fest', 'Event', '', 'https://www.impactfest.nl/', 'ImpactCity the Hague', 'Open to all', 'Free', ''),
(144, 'LSH Breakfast', 'Event', '', 'https://rotterdamsquare.nl/', 'Rotterdam Square', 'Open to all', 'Free', ''),
(145, 'Monthly Climate Tech Community Sessions', 'Event', '', 'https://platformzero.co/pz-events/', 'Platform Zero', 'Open to all', 'Free', ''),
(146, 'Monthly Meetup', 'Event', '', 'https://cic.com/attend-an-event/', 'CIC Rotterdam', 'Open to all', 'Free', ''),
(147, 'NL Space Campus Network & Drinks', 'Event', '', 'https://www.nlspacecampus.eu/nlspaceweek/nl-space-campus-network-drinks-xl/', 'Space Campus', 'Open to all', 'Free', ''),
(148, 'NL Space Week', 'Event', '', 'https://www.nlspacecampus.eu/nlspaceweek/', 'Space Campus', 'Open to all', 'Free', ''),
(149, 'NL Startup Competition', 'Event', '', 'https://nlstartupcompetition.com/', 'Erasmus Enterprise', 'Application required', 'Free', ''),
(150, 'Philips Innovation Award', 'Event', '', 'https://www.phia.nl/', 'Philips Innovation Award', 'Application required', 'Free', ''),
(151, 'PLNT Festival', 'Event', '', 'https://plnt.nl/events/', 'PLNT', 'Open to all', 'Free', ''),
(152, 'RoboCafé', 'Event', '', 'https://robohouse.nl/activities/events/robocafe-2024/', 'Robohouse (TU Delft)', 'Open to all', 'Free', ''),
(153, 'Scale-up UnConference', 'Event', '', 'https://www.tudelftcampus.nl/event/scale-up-unconference/', 'Yes!Delft', 'Open to all', 'Free', ''),
(154, 'SHE LEADS+ Annual Event', 'Event', '', 'https://www.ece.nl/she-leads/', 'ECE', 'Open to all', 'Free', ''),
(155, 'Startup Investor Dinner', 'Event', '', 'https://yesdelft.com/events/startup-investor-dinner-2025/', 'Yes!Delft', 'Application required', 'Free', ''),
(156, 'Synergy Hackathon', 'Event', '', 'https://www.thegreenvillage.org/event/synergy-hackathon/', 'The Green Village', 'Open to all', 'Free', ''),
(157, 'TechSocial', 'Event', '', 'https://rotterdamtechsocial.com/', '42Workspace / ECE / Yes!Delft', 'Open to all', 'Free', ''),
(158, 'Top 250 Masterclasses', 'Event', '', '', 'ECE', 'Application required', 'Free', ''),
(159, 'TU Delft Impact Contest', 'Event', '', 'https://tudelftcontest.nl/', 'TU Delft', 'Application required', 'Free', ''),
(160, 'Upstream Festival', 'Event', '', 'https://www.upstreamfestival.com/', 'Up!Rotterdam', 'Open to all', 'Free', ''),
(161, 'Photovoltaic Systems Summer School', 'Event', '', 'https://www.tudelft.nl/en/ewi/', 'TU Delft', 'Application required', 'Paid', '')
on conflict (id) do nothing;
